// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzYsSwBPPnu6l5TsMiPIViTDNjLk238_w',
    appId: '1:7167791596:web:a75bd634081a0d6fb370c9',
    messagingSenderId: '7167791596',
    projectId: 'social-app-ec839',
    authDomain: 'social-app-ec839.firebaseapp.com',
    storageBucket: 'social-app-ec839.firebasestorage.app',
    measurementId: 'G-FPT9WFY5HR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC41eNWKM8GTdww6SeajzrwVeVSACMhYeA',
    appId: '1:7167791596:android:766316ddd6ebe04db370c9',
    messagingSenderId: '7167791596',
    projectId: 'social-app-ec839',
    storageBucket: 'social-app-ec839.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj4nzX9i2HoB9njXfUGsBVUWu46x3xYaM',
    appId: '1:7167791596:ios:40d9f425631eaeebb370c9',
    messagingSenderId: '7167791596',
    projectId: 'social-app-ec839',
    storageBucket: 'social-app-ec839.firebasestorage.app',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzYsSwBPPnu6l5TsMiPIViTDNjLk238_w',
    appId: '1:7167791596:web:71a4b7a46ee663e2b370c9',
    messagingSenderId: '7167791596',
    projectId: 'social-app-ec839',
    authDomain: 'social-app-ec839.firebaseapp.com',
    storageBucket: 'social-app-ec839.firebasestorage.app',
    measurementId: 'G-4H1JWSP2DW',
  );
}
